### ISSUE TITLE
Include exclude parameter

### ISSUE THREAD

**Issue by krisdestruction** [myint/autoflake#11]
Add `--exclude` parameter to exclude files with a certain pattern

**Comment by myint** [comment]
We just need to replicate what we do in [`find_files()`](https://github.com/hhatto/autopep8/blob/ce4c6333a7bc3a7a83ef4e65591082e67d82a180/autopep8.py#L3724) in `autopep8`.

**Comment by yasirroni** [comment]
I write it here that you can use star for exclude file with pattern such as 'test_*'.

Example:

```yaml
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--recursive',
          '--remove-all-unused-imports',
          '--ignore-init-module-imports',
          '--remove-unused-variables',
          '--exclude',
          'test_*',
          '--'
        ]
```
