### ISSUE TITLE
Option to flag certain unused imports as exceptions

### ISSUE THREAD

**Issue by chrisspen** [myint/autoflake#20]
I have a Django app whose traditional `models.py` file is actually a `models` package. To keep it compatible with other Django functions, the package's `__init__.py` contains:

    from .base import *

When I ran `autoflake --in-place --remove-all-unused-imports src` it stripped out this line, breaking my entire app, and the cause wasn't immediately obvious.

Still, `autoflake` correctly removed a ton of other unused imports. Is there any option to flag certain lines as exceptions, so you can run `autoflake` on an entire codebase but ensure that it won't incorrectly remove a line that's an exception to the rule?

Pylint supports this feature with a syntax like:

    some_line # pylint: disable=rule-name

Does `autoflake` support anything like that?

**Comment by myint** [comment]
I think it will leave the import there if you have any comment inline.

```python
from .base import *  # Hello.
```
