### ISSUE TITLE
Support type hints for Python 2.7 and straddling code

### ISSUE THREAD

**Issue by hackerkid** [myint/autoflake#24]
```py
from typing import List

def hello(): # type: () -> None
    print 'hello'

class Example:
    def method(self, lst, opt=0, *args, **kwargs):
        # type: (List[str], int, *str, **bool) -> int
        print("Do stuff")
```
Running `autoflake --remove-all-unused-imports ` would remove `from typing import List`. This should not be the case as `List` import is used for defining the type.

* https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code
* mypy is a static type checker for Python and uses type annotation in comments for supporting python2.7 code. http://mypy.readthedocs.io/en/latest/python2.html
* http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/

**Comment by myint** [comment]
`autoflake` is just removing what `pyflakes` reports, so it might be good to report it [there](https://github.com/PyCQA/pyflakes).

**Comment by jaens** [comment]
Looks like there's already an issue about type comments for pyflakes: PyCQA/pyflakes#247

**Comment by asottile** [comment]
this should just work now with the latest pyflakes 2.x after my patch here: https://github.com/PyCQA/pyflakes/pull/400
