### ISSUE TITLE
Support for running autoflake on all files in a directory

### ISSUE THREAD

**Issue by EmilStenstrom** [myint/autoflake#34]
I've tried to find a magic flag or hack that lets to run autoflake on all files in a directory. Like what flake8 and isort have. Is this something that is possible, or even desirable? 

A workaround is to use:
```
find . -name '*.py' | xargs autoflake --in-place --remove-all-unused-imports --remove-unused-variables
```

But this doesn't work on windows, and requires some knowhow into how find and xargs work, something that likely many beginners lack.

Thanks for a great project!

**Comment by myint** [comment]
See `--recursive` (or `-r` for short).

**Comment by EmilStenstrom** [comment]
@myint Oh, how could I have missed that. For others reading this, the command to use is:

```bash
autoflake --recursive .
```
