### ISSUE TITLE
Don't remove imports from __init__.py

### ISSUE THREAD

**Issue by NeilGirdhar** [myint/autoflake#35]
A typical way to set up a project is to have the modules specify `__all__` variables and then have the `__init__.py` `from .module_name import *`.  This causes autoflake to remove all of the imports.

Please consider leaving the imports in `__init__.py`.

**Comment by myint** [comment]
I think having such an option makes sense. It might be useful to get some metrics on how common this is. That would help us get an idea on whether this new behavior should be an option or the default.

Currently, `autoflake` can only exclude `__init__.py` files via `--exclude=__init__.py`. But that will make `autoflake` completely ignore it. And `--exclude` is only relevant to recursive mode.

**Comment by NeilGirdhar** [comment]
It's pretty standard: e.g., https://github.com/numpy/numpy/blob/master/numpy/linalg/__init__.py

It's better to do it this way than to explicitly list things in the `__init__.py` otherwise changes to exported names have to be done in two places (`__all__` in the module, and the `import` statement in `__init__.py`).

**Comment by NeilGirdhar** [comment]
Thanks!

**Comment by CLiu13** [comment]
Working on this issue, may I be assigned to it? Thanks!

**Comment by tiangolo** [comment]
Just a note, as I was having a similar issue and came here before but didn't find this info.

You can exclude a single line adding a comment `# noqa`, like:

```Python
from .endpoints import role, token, user, utils  # noqa
```

I also submitted a PR adding that to the docs: https://github.com/myint/autoflake/pull/43
