### ISSUE TITLE
running autoflake in multiple directories?

### ISSUE THREAD

**Issue by mpuri14** [myint/autoflake#39]
I am looking to find all python files in my d:\ and run autoflake on it? how would i do this? 

I saw a mention of the -r parameter but it did not work for me.

**Comment by myint** [comment]
This should work:

```
autoflake -r directory_path_here
```

> but it did not work for me.

Can you provide additional details on your test case ?

**Comment by mpuri14** [comment]
I saw what my problem was and was able to fix it. thanks.

On another note, I want to create a backup of files only where autoflake was run. How would I do this?

**Comment by myint** [comment]
`autoflake` doesn't support making backup files. But feel free to create an issue (or pull request) for that enhancement.
