### ISSUE TITLE
Handle imports for type annotations

### ISSUE THREAD

**Issue by dmey** [myint/autoflake#40]
Currently, import from type annotations are removed.
E.g.
``` py
from typing import Any

a = None    # type: Any
```
becomes
```py
a = None    # type: Any
```

**Comment by myint** [comment]
You may want to take a look at https://github.com/PyCQA/pyflakes/issues/247. `autoflake`'s actions are informed by the output of `pyflakes`.

**Comment by asottile** [comment]
this is probably (magically) fixed now that that is implemented :tada:

**Comment by myint** [comment]
@asottile Thanks!
