### ISSUE TITLE
call autoflake as python module, and run on string instead of file?

### ISSUE THREAD

**Issue by gotexis** [myint/autoflake#47]
I understand since this module is written in python, there must be some way to run the module programmatically (that is, not through subprocess).

I wonder if this is documented?

Also, instead of running on file, it would be better to run on string if possible :)

**Comment by myint** [comment]
See unit tests for example usage:

https://github.com/myint/autoflake/blob/61b09b321a5604b643c581475827958c7c03ffcd/test_autoflake.py#L539-L557
