### ISSUE TITLE
--check flag isn't available

### ISSUE THREAD

**Issue by SaturnFromTitan** [myint/autoflake#50]
The documentation is pointing to a flag `--check`, but trying to run `autoflake --check my_file.py` I receive the following error:
```
usage: autoflake [-h] [-i] [-r] [--exclude globs] [--imports IMPORTS]
                 [--expand-star-imports] [--remove-all-unused-imports]
                 [--remove-duplicate-keys] [--remove-unused-variables]
                 [--version]
                 files [files ...]
autoflake: error: unrecognized arguments: --check
```

I'm on version `autoflake 1.2`

Is there a known work-around for this? I need this to include it in my CI integration. I would also be fine with the regular output of `autoflake my_file.py`, but the error code is always 0, even if it discovers changes...

**Comment by myint** [comment]
This feature wasn't released to PyPI yet. To get the latest changes from Git, you can install from this repository rather than PyPI.

We've been due for a PyPI release so I went ahead and released the latest code to PyPI in version [1.3](https://pypi.org/project/autoflake/1.3/).
