### ISSUE TITLE
Is fix multiple spaces before key word available ?

### ISSUE THREAD

**Issue by ishandutta2007** [myint/autoflake#55]
I guess the following would fall under the same category, I was wondering is these are automatable or planned to be done in future releases.
- Multiple spaces before keyword
- Missing whitespace after keyword
- no space space around keyword
- unexpected spaces around keyword
- trailing whitespaces
- too many blank lines
- expected 2 blank lines, found 1

**Comment by myint** [comment]
Sounds more like a job for [`autopep8`](https://github.com/hhatto/autopep8).

**Comment by ishandutta2007** [comment]
@myint But Flake8 also does that.

**Comment by ishandutta2007** [comment]
Ok got it, this package is an automation of pyflake and not flake8. Ideally autoflake+autopep8 should be called autoflake8.
