### ISSUE TITLE
Fix warnings from flake8-comprehensions

### ISSUE THREAD

**Issue by Zac-HD** [myint/autoflake#60]
[`flake8-comprehensions`](https://pypi.org/project/flake8-comprehensions/) is a lovely plugin to warn about inefficient creation of and operations on collections - and each of the warnings suggests a simple rewrite rule to resolve them.  I'm not sure if this is really in scope for `autoflake`, but thought it worth suggesting an optional flag to do so 😄

**Comment by myint** [comment]
Thanks for pointing out `flake8-comprehensions`! As you hint at in the linked issue, I think this might better align with a tool with broader scope `pyflakes`, which `autoflake` focuses on.
