### ISSUE TITLE
autoflake doesn't work correctly with this imports

### ISSUE THREAD

**Issue by therealmaxmoon** [myint/autoflake#83]
First I thought autoflake doesn't work at all and tried to add `import time`. And it worked, it removed this line. But my file has the following imports, which autoflake let there even if they aren't used:
```
import requests
import arrow
import simplejson as json
from colored import fore, back, style
from my_helpers import *
```

I used following command:

`autoflake --in-place --remove-unused-variables my_python_script.py`

**Comment by EdvardM** [comment]
To be safe, autoflake removes by default only those imports which are part of standard library, as others could have side-effects beyond just importing set of objects from given namespace. 

To remove all unused imports, use `--remove-all-unused-imports`
